### ISSUE TITLE
There is a problem with the VRD feature data set

### ISSUE THREAD

**Issue by lianjiawei** [Cadene/block.bootstrap.pytorch#2]
When I ran bash block/datasets/scripts/download_vrd.sh to download the feature file and unzip it, I found it could not be unzipped. I think there was something wrong with the compression of the data set.

**Comment by Cadene** [comment]
@lianjiawei Thanks for submitting this issue.

 It should be fixed now. You can download the features again.

**Comment by fomalhaut-b** [comment]
hi @Cadene still facing this issue
