### ISSUE TITLE
GPU memory and multi-gpu use

### ISSUE THREAD

**Issue by wenzezhang** [Cadene/block.bootstrap.pytorch#3]
Hi, thanks for shared this work,  i want to know how many gpu memory it cost when training a vqa model ？ Does this script support multiple GPUs?

**Comment by Cadene** [comment]
@wenzezhang we use only one GPU (GTX 1080) to run a VQA model.

This script supports multiple GPUs: [here](https://github.com/Cadene/block.bootstrap.pytorch/blob/master/block/models/networks/factory.py#L32)

To run with multiple GPUs: `export CUDA_VISIBLE_DEVICES=0,1` or `export CUDA_VISIBLE_DEVICES=0,1,2,4`, etc.

**Comment by wenzezhang** [comment]
ok, it works thanks !

**Comment by wenzezhang** [comment]
it works thanks !
