### ISSUE TITLE
Getting an error on skip-thoughts 

### ISSUE THREAD

**Issue by tbozinis** [Cadene/block.bootstrap.pytorch#8]
In line 61: `params = numpy.load(path_params, encoding='latin1') # to load from python2`
Im getting an error from numpy that cannot load pickle with `allow_pickle=False`.

_I have installed skip-thoughts with pip as instructed on the README_

**Comment by Cadene** [comment]
@tbozinis thanks for your interest :)

Could you try this? https://github.com/Cadene/murel.bootstrap.pytorch/issues/8

**Comment by tbozinis** [comment]
I did actually added `allow_pickle=True` my self (even from your [vqa.pytorch](https://github.com/Cadene/vqa.pytorch)). The strange thing is that this particular param of `numpy.load` is True by default... Never the less, thank you for the answer.
