### ISSUE TITLE
AttributeError: module 'block' has no attribute 'external

### ISSUE THREAD

**Issue by Zzmonica** [Cadene/block.bootstrap.pytorch#9]
as mentioned in title, here comes an error that the program can not find the block.external. And I reinstalled the block from source, still can not import it. 
Any suggestion?
Thanks！

**Comment by Cadene** [comment]
@Zzmonica thanks for your interest :)

Did you use the recursive flag?
```
cd $HOME
git clone --recursive https://github.com/Cadene/block.bootstrap.pytorch.git
cd block.bootstrap.pytorch
ls block/external # not empty
python setup.py install
```

Note: When I develop, I prefer to create a link to block in my project:
```
cd $HOME
cd myproject
ln -s ../block.bootstrap.pytorch/block .
ls block # not empty
```

**Comment by Zzmonica** [comment]
Thanks for your advice!  
Actually, I copyed the external folder and the options folder to my conda virtual environments' corresponding directory, and it seems that work.
